# Generated by Django 4.2.1 on 2023-05-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sancho", "0002_alter_backtest_name_alter_backtest_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="backtest",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="metrics",
            name="period_type",
        ),
        migrations.AddField(
            model_name="backtest",
            name="period_type",
            field=models.CharField(
                choices=[("IS", "In Sample"), ("OS", "Out of Sample"), ("ISOS", "ALL")],
                default="ISOS",
                max_length=4,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="backtest",
            unique_together={("name", "optimization", "period_type")},
        ),
    ]
