# Generated by Django 4.2.1 on 2023-05-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sancho", "0003_alter_backtest_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backtest",
            name="initial_balance",
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=15),
        ),
        migrations.AlterField(
            model_name="metrics",
            name="avg_loss",
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name="metrics",
            name="avg_win",
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name="metrics",
            name="dd",
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name="metrics",
            name="ep",
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name="metrics",
            name="kratio",
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name="metrics",
            name="loss",
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name="metrics",
            name="max_exposure",
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name="metrics",
            name="max_lots",
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name="metrics",
            name="min_lots",
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name="metrics",
            name="pct_winner",
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name="metrics",
            name="pf",
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name="metrics",
            name="profit",
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name="metrics",
            name="rf",
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name="metrics",
            name="sharpe_ratio",
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name="metrics",
            name="sqn",
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
    ]
