# Generated by Django 4.2.1 on 2023-05-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sancho", "0004_alter_backtest_initial_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backtest",
            name="timeframe",
            field=models.CharField(
                choices=[
                    ("M1", "M1"),
                    ("M5", "M5"),
                    ("M15", "M15"),
                    ("M30", "M30"),
                    ("H1", "H1"),
                    ("H4", "H4"),
                    ("D1", "D1"),
                    ("W", " W"),
                    ("M", "M"),
                ],
                default="H4",
                max_length=3,
            ),
        ),
    ]
